name = "bulma-kiss"
license = "MIT"
licenselink = "https://github.com/dkozel/hugo-bulma-kiss/blob/master/LICENSE"
description = "Responsive mobile-first Bulma-powered minimalistic Hugo theme for an individual or small organization or as a starter for grander ideas."
homepage = "https://github.com/dkozel/hugo-bulma-kiss"
tags = ["blog","mobile","bulma","responsive", "minimal"]
features = ["responsive","atom","bulma","bulmaswatch"]
min_version = "0.109.0"
updated = "2022-12-31"

[author]
  name = "Derek Kozel"
  homepage = "https://github.com/dkozel"

